use_frameworks!

target 'Cocoarreios_Example' do
  pod 'Cocoarreios', :path => '../'

  target 'Cocoarreios_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
