use_frameworks!

target 'Cocoarreios_Example' do
  pod 'Cocoarreios', :path => '../'

  target 'Cocoarreios_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
